
server:
    servlet:
        # 한글깨짐 처리 
        encoding:
            force-response: true
    # error:
    #     whitelabel:
    #         enabled: false
    #     path: /errors

cloud:
    aws:
        s3:
            bucket: mention-bucket.bucket
        region:
            static: ap-northeast-2
            auto: false
        stack:
            auto: false
        credentials:
<<<<<<< HEAD
            access-key: AKIA2UC3EZ72D6WRUE4B
=======
            access-key: AKIA2UC3EZ72I3S4NIGI
<<<<<<< HEAD
>>>>>>> 6bb71b404eaade85f63931b4ad85bd8a4c7a9ce0
            secret-key: 
=======
            secret-key:
>>>>>>> 46f02b1 (ui fix)

spring:
    output:
        ansi:
            enabled: always
    
    # mustache 설정
    mustache:
        prefix: classpath:templates/
        check-template-location: true
        suffix: .html # .html파일을 모두 mustache으로 인식
        servlet:
            cache: false
    # 데이터베이스 설정 
    datasource:
        url: jdbc:mysql://nasdaq-db.clcgk04eeism.ap-northeast-2.rds.amazonaws.com:3306/nasdaq?userSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
        username: admin
        password: admin1234
        driver-class-name: com.mysql.cj.jdbc.Driver
    # jpa 설정 
    jpa:
        hibernate:
            ddl-auto: update
            transaction:
                jta:
                    platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                dialect:
                    org.hibernate.dialect.MySQLDialect
   
    sql:
        init:
            platform: mysql
            mode: always
    devtools:
        livereload:
            enabled: true
        freemarker:
            cache: false
        thymeleaf:
            cache: false



            
        
